#!/bin/sh

#. "/usr/lib/pm-utils/pm-functions"

date >> log
tty >> log

echo "luks: actually suspending" >> log
#do_suspend
echo -n "standby" > /sys/power/state

echo "luks: suspending" >> log
/sbin/cryptsetup luksSuspend /dev/mapper/sda5_crypt

echo "luks: resuming" >> log
/sbin/cryptsetup luksResume /dev/mapper/sda5_crypt

